install:
    crash_reporting:
        enabled: true
        type: "crashpad"
    game-settings:
        accountId: 2603799230186848
        modified: false
        timestamp: 0
    gameflow-patcher-lock: 1734455679306
    gameflow-process-info: null
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "en_GB"
        region: "EUW"
    lcu-settings:
        accountId: 2603799230186848
        modified: false
        timestamp: 0
    patcher:
        client_migrated: true
        client_patcher_available: true
        game_migrated: true
        game_patcher_available: true
        locales:
        - "en_GB"
        toggles:
            new_client_patcher: 0
            new_game_patcher: 0
    perks-settings:
        accountId: 2603799230186848
        modified: false
        timestamp: 0
    riotclient-upgrade:
        seq-success-count: 108
        success-count: 108
    rso-auth:
        install-identifier: "7358ee5472f84d43b1162fad48d4f405"
    tft-settings:
        accountId: 2603799230186848
        modified: false
        timestamp: 0
    tft-team-plans-settings:
        accountId: 2603799230186848
        modified: false
        timestamp: 0
