install:
    crash_reporting:
        enabled: true
        type: "crashpad"
    game-settings:
        accountId: 3018421651285248
        modified: false
        timestamp: 0
    gameflow-patcher-lock: 1740965287043
    gameflow-process-info: null
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "en_GB"
        region: "EUW"
    lcu-settings:
        accountId: 3018421651285248
        modified: false
        timestamp: 0
    patcher:
        client_migrated: true
        client_patcher_available: true
        game_migrated: true
        game_patcher_available: true
        locales:
        - "en_GB"
        toggles:
            new_client_patcher: 0
            new_game_patcher: 0
    perks-settings:
        accountId: 3018421651285248
        modified: false
        timestamp: 0
    riotclient-upgrade:
        seq-success-count: 115
        success-count: 115
    rso-auth:
        install-identifier: "896e6c9edded6548bdc1c9eea4a52485"
    tft-settings:
        accountId: 3018421651285248
        modified: false
        timestamp: 0
    tft-team-plans-settings:
        accountId: 0
        modified: false
        timestamp: 0
